In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#load Dataset
df=pd.read_csv("data_Proj_2.csv")
df.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [3]:
#Converting target column into numeric
# We'll use dictionary encoding
Class_dict={"DERMASON":0,"SIRA":1,"SEKER":2,"HOROZ":3,"CALI":4,"BARBUNYA":5,"BOMBAY":6}
df["Class_enc"]=df.Class.map(Class_dict)

In [4]:
df1=df.drop(["Class"],axis=1)

In [5]:
df1

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

       Class_enc  
0              2  
1              2  
2              2  
3              2  
4              2  
...          ...  
13606          0  
13607          0  
13608          0  
13609          0  
13610          0  

[13611 rows x 17 columns]

### Min-Max Scaler

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
data_scaled=scaler.fit_transform(df1.iloc[:, :-1])
df1=pd.DataFrame(data_scaled,columns=df1.columns[:-1])
df1.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  0.034053   0.058574         0.044262         0.152142      0.122612   
1  0.035500   0.077557         0.030479         0.178337      0.051577   
2  0.038259   0.068035         0.052633         0.158190      0.131521   
3  0.040940   0.082942         0.048548         0.177691      0.091623   
4  0.041504   0.065313         0.032862         0.200679      0.025565   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.477797    0.033107       0.070804  0.671024  0.922824   0.934823   
1      0.278472    0.034991       0.073577  0.735504  0.871514   0.793138   
2      0.496448    0.037126       0.078816  0.716671  0.932141   0.914511   
3      0.403864    0.041389       0.083854  0.731365  0.761614   0.826871   
4      0.165680    0.040123       0.084906  0.700538  0.949832   0.988408   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
0     0.786733      0.593432      0.833049      0.750996      0.980620  
1     0.903549      0.547447      0.967316      0.884987      0.974979  
2     0.773514      0.582016      0.800942      0.736200      0.987196  
3     0.829912      0.552408      0.854744      0.799846      0.893675  
4     0.951583      0.510741      1.000000      0.941770      0.989116

In [7]:
X=df1
y=df["Class_enc"]

In [8]:
print("X Shape: ",X.shape)
print("y Shape: ", y.shape)

X Shape:  (13611, 16)
y Shape:  (13611,)


In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
print("X_train: ",X_train.shape)
print("X_test: ",X_test.shape)
print("y_train: ",y_train.shape)
print("y_test: ",y_test.shape)

X_train:  (10888, 16)
X_test:  (2723, 16)
y_train:  (10888,)
y_test:  (2723,)


### 1.Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

D:\Users\ROHIT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
#Accuracy On training set
print("Accuracy on training : ",lr.score(X_train,y_train))
#Accuracy On testing set
print("Accuracy on testing : ",lr.score(X_test,y_test))

Accuracy on training :  0.9171565025716385
Accuracy on testing :  0.9203084832904884


In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,roc_auc_score,roc_curve
y_pred=lr.predict(X_test)
print("confusion matrix:\n",
      confusion_matrix(y_test,y_pred))
print("\n")
print("Accuracy score:" ,accuracy_score(y_test,y_pred))
print("recall: ",recall_score(y_test,y_pred,average="micro"))
print("Precison: ",precision_score(y_test,y_pred,average="micro"))
print("F1-score: ", f1_score(y_test,y_pred,average="micro"))
print("Specifity: ",confusion_matrix(y_test, y_pred)[0,0] / (confusion_matrix(y_test, y_pred)[0,0] + confusion_matrix(y_test, y_pred)[0,1]))

confusion matrix:
 [[602  58  11   0   0   0   0]
 [ 41 479   8   7   0   1   0]
 [ 13  10 385   0   0   5   0]
 [  4   8   0 391   5   0   0]
 [  0   5   0   4 299   9   0]
 [  0  10   2   1  15 233   0]
 [  0   0   0   0   0   0 117]]


Accuracy score: 0.9203084832904884
recall:  0.9203084832904884
Precison:  0.9203084832904884
F1-score:  0.9203084832904884
Specifity:  0.9121212121212121


### 2.SVM

In [14]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(X_train,y_train)

SVC()

In [15]:
#Accuracy On training set
print("Accuracy on training : ",sv.score(X_train,y_train))
#Accuracy On testing set
print("Accuracy on testing : ",sv.score(X_test,y_test))

Accuracy on training :  0.9246877296105804
Accuracy on testing :  0.9280205655526992


In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,roc_auc_score,roc_curve
y_pred=sv.predict(X_test)
print("confusion matrix:\n",
      confusion_matrix(y_test,y_pred))
print("\n")
print("Accuracy score:" ,accuracy_score(y_test,y_pred))
print("recall: ",recall_score(y_test,y_pred,average="micro"))
print("Precison: ",precision_score(y_test,y_pred,average="micro"))
print("F1-score: ", f1_score(y_test,y_pred,average="micro"))
print("Specifity: ",confusion_matrix(y_test, y_pred)[0,0] / (confusion_matrix(y_test, y_pred)[0,0] + confusion_matrix(y_test, y_pred)[0,1]))

confusion matrix:
 [[612  51   7   1   0   0   0]
 [ 45 480   5   5   0   1   0]
 [ 12   8 388   0   0   5   0]
 [  4   6   0 392   5   1   0]
 [  0   3   0   3 304   7   0]
 [  0   9   0   1  17 234   0]
 [  0   0   0   0   0   0 117]]


Accuracy score: 0.9280205655526992
recall:  0.9280205655526992
Precison:  0.9280205655526992
F1-score:  0.9280205655526992
Specifity:  0.9230769230769231


### 3.Decision tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [18]:
#Accuracy On training set
print("Accuracy on training : ",dt.score(X_train,y_train))
#Accuracy On testing set
print("Accuracy on testing : ",dt.score(X_test,y_test))

Accuracy on training :  1.0
Accuracy on testing :  0.892398090341535


In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,roc_auc_score,roc_curve
y_pred=dt.predict(X_test)
print("confusion matrix:\n",
      confusion_matrix(y_test,y_pred))
print("\n")
print("Accuracy score:" ,accuracy_score(y_test,y_pred))
print("recall: ",recall_score(y_test,y_pred,average="micro"))
print("Precison: ",precision_score(y_test,y_pred,average="micro"))
print("F1-score: ", f1_score(y_test,y_pred,average="micro"))
print("Specifity: ",confusion_matrix(y_test, y_pred)[0,0] / (confusion_matrix(y_test, y_pred)[0,0] + confusion_matrix(y_test, y_pred)[0,1]))

confusion matrix:
 [[593  62  11   4   0   1   0]
 [ 61 446  12  10   1   6   0]
 [ 22  12 377   0   0   2   0]
 [  3   8   0 382  11   4   0]
 [  0   2   1   5 286  23   0]
 [  0   7   2   1  22 229   0]
 [  0   0   0   0   0   0 117]]


Accuracy score: 0.892398090341535
recall:  0.892398090341535
Precison:  0.892398090341535
F1-score:  0.892398090341535
Specifity:  0.9053435114503817
